# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install dependencies
      run: npm install
      
    - name: Generate zip file
      run: TOKEN=${{ vars.TOKEN }} node index.js

    - name: Find generated zip file
      id: find-zip
      run: |
        ZIP_FILE=$(find . -name '*.zip' -type f -printf "%T@ %p\n" | sort -n | tail -n 1 | cut -d' ' -f2-)
        echo "::set-output name=zip-path::$ZIP_FILE"

    - name: Upload zip file as artifact
      uses: actions/upload-artifact@v2
      with:
        name: generated-zip
        path: ${{ steps.find-zip.outputs.zip-path }}

    - name: Get artifact download URL
      id: artifact-download-url
      run: echo "::set-output name=url::$(echo "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts/$(basename "${{ steps.find-zip.outputs.zip-path }}")")"

    - name: Pass URL to npm run handoff
      run: npm run handoff ${{ steps.artifact-download-url.outputs.url }}
